name: Deploy Notebooks to Databricks
run-name: ${{ github.actor }} is testing out databricks cli
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "install databricks cli"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dbx cli
        run: |
          pip install -U urllib3 requests
          pip install --upgrade urllib3
          pip install --upgrade chardet
          pip install --upgrade databricks-cli
      - name: Deploy Notebooks to Databricks
        run: |
          databricks workspace ls
        env:
          DATABRICKS_HOST: https://adb-3778382070723255.15.azuredatabricks.net
          DATABRICKS_TOKEN: dapiee8d2ae80ba064d0de7b4a04ca2e93e5
      - run: echo "üçè This job's status is ${{ job.status }}."
